#!/bin/bash
# Script to enable reloading of PDFs in Skim on macOS

file="$1"

/usr/bin/osascript << EOF
  set theFile to POSIX file "${file}" as alias
  tell application "Skim"
  activate
  set theDocs to get documents whose path is (get POSIX path of theFile)
  if (count of theDocs) > 0 then revert theDocs
  open theFile
  end tell
EOF

